### PR TITLE
Support missing future release date in uplift_info

### PR DESCRIPTION
**Pull request by La0**
Needed for some uplifts tests in uplift-bot

### CODE REVIEW

**Comment by marco-c** [comment]
Which one is missing? We should fix the source of the data.

**Comment by La0** [comment]
The beta release is not listed, so any request to get the next release on an uplift bug on beta will throw an Exception about the `min([])` list being empty.

I return `None` from the versions file in this case, but could throw an Exception instead.

**Comment by marco-c** [comment]
> I return None from the versions file in this case, but could throw an Exception instead.

Let's raise an exception, or we could infer the beta release date from the release release date.

**Comment by La0** [comment]
@marco-c I dived a bit more into the ICS calendar describing future releases, and noticed that the next releases are indeed present (up until version 64!). The regex in `libmozdata/versions.py` did not report them because it was not case insensitive.

My patch now lists all these previously ignored versions, and simply raises an exception if no future date is found.

**Comment by marco-c** [comment]
> @marco-c I dived a bit more into the ICS calendar describing future releases, and noticed that the next releases are indeed present (up until version 64!). The regex in libmozdata/versions.py did not report them because it was case sensitive.
> 
> My patch now lists all these previously ignored versions, and simply raises an exception if no future date is found.

Awesome! Thanks.

**Pull request merged**
