### PR TITLE
Remove support for Socorro ProductVersions (#128)

### LINKED ISSUE #128: remove socorro ProductVersions
`ProductVersions` is deprecated and I'm removing it in the next week or two. We should remove it from libmozdata, too.

### PR DESCRIPTION
**Pull request by willkg**
Fixes #128.

### CODE REVIEW

**Comment by willkg** [comment]
There's one thing that needs to get done that I couldn't figure out what to do with. The redash test uses `ProductVersions` to get a list of versions from Socorro to use in the redash test:

https://github.com/mozilla/libmozdata/blob/fc2e6dc1328bdb242c1cfe8d4687e6078b255fe3/tests/test_redash.py#L25

I don't know what to replace that with. If there was a Buildhub lib, then maybe we could replace it with that.

Thoughts?

**Comment by marco-c** [comment]
What if we simply used the versions we have in `v`, which we get at https://github.com/mozilla/libmozdata/blob/fc2e6dc1328bdb242c1cfe8d4687e6078b255fe3/tests/test_redash.py#L18?

**Comment by willkg** [comment]
I don't know what the shape is of the things there, so I don't have any thoughts on whether this would work. I also can't get the tests to run and pass, so I can't try this out. But maybe that's a way forward? Either that or hard-coding the data somehow?

**Comment by willkg** [comment]
^^^ That rebases this branch against master.

Thank you, @marco-c!

**Pull request merged**
