### PR TITLE
Add UA in request headers for phabricator and lando connectors.

### PR DESCRIPTION
**Pull request by abpostelnicu**

### CODE REVIEW

**Review by suhaibmujahid — APPROVED** [review]
LGTM

**Comment by marco-c** [comment]
@abpostelnicu https://github.com/mozilla/libmozdata/blob/aa80079c9a036531606942e175a25400fa69cfe3/libmozdata/phabricator.py#LL50C5-L50C31 is still using the default user agent.

**Comment by marco-c** [comment]
@abpostelnicu if you don't set it, it will use the default.

**Comment by marco-c** [comment]
Ah, it's probably called in some user of the library, maybe in code-review

**Comment by marco-c** [comment]
If it isn't used anywhere we could remove it.

**Pull request merged**
