### PR TITLE
Add functions to get spikes in data

### PR DESCRIPTION
**Pull request by calixteman**
Use the Grubb's test to get the outliers

### CODE REVIEW

**Comment by marco-c** [comment]
LGTM.
Needs to be updated in order to merge.

**Comment by marco-c** [comment]
Also need to `git add` the new mock files.

**Comment by calixteman** [comment]
I replaced urlopen by requests.get to have a mock file

**Comment by sylvestre** [comment]
Maybe you could add today bug (the Norton top crash) as test case too

**Comment by calixteman** [comment]
sure

**Pull request merged**
